### PR TITLE
Adding Icons to Alert Messages

### LINKED ISSUE #686: Add icons to alerts
[Alerts · Bootstrap v5.3](https://getbootstrap.com/docs/5.3/components/alerts/#icons)

### PR DESCRIPTION
**Pull request by AnukratiMehta**
# Closes #686 

## Description

This pull request adds icons to all the alert messages in the application.

### CODE REVIEW

**Review by dougwaldron — CHANGES_REQUESTED** [review]
Thanks for this PR, @AnukratiMehta! This is going to be really nice to have! I need two changes though before I can merge it. The first will be simple, but the second is a little trickier...

First, the validation summary should only be displayed when there are errors. [This line in the CSS](https://github.com/AnukratiMehta/complaint-tracking/blob/bf827bd117284e123dec973bb4526b678932948d/src/WebApp/wwwroot/css/site.css#L268-L270) hides the summary when there are no errors:

```css
.validation-summary-valid {
    display: none;
}
```

Unfortunately, when you added the `d-flex` class to the summary, it overrides the display property so the validation summary is no longer hidden when empty:
image

This should be easy to fix by adding another line to the CSS file:

```css
.validation-summary-valid.d-flex {
    display: none !important;
}
```

The second change I'd like is for the icon for alerts to change based on the alert class (this change *only* applies to the "_AlertPartial.cshtml" file, not the validation summaries). The [Bootstrap docs give this example](https://getbootstrap.com/docs/5.3/components/alerts/#icons):
image

The "_AlertPartial.cshtml" model has an `AlertContext` property that can be used to select the correct icon. [`AlertContext` is an enum](https://github.com/AnukratiMehta/complaint-tracking/blob/bf827bd117284e123dec973bb4526b678932948d/src/WebApp/Models/DisplayMessage.cs#L21-L29) with six possible values. I would want the expected icons for Success, Danger, Warning, and Info; but no icon displayed for Primary or Secondary. Please let me know if that makes sense... Thanks!

**Comment by AnukratiMehta** [comment]
Thanks for the detailed instructions @dougwaldron. Since I am not well-versed in .NET development, the second change was a little challenging for me. Please check and let me know if I was able to get it right. Thanks!

**Review by dougwaldron — CHANGES_REQUESTED** [review]
This is great! Everything is working perfectly and I'm getting the correct icons in all places. There's just one detail that needs to be tidied up now. 

I know that .NET Razor syntax can be odd since it switches between C# and HTML, and sometimes it doesn't work the way you expect. But in the switch statement in "_AlertPartial", you can just output the SVG code directly instead of saving everything to a string first:

```razor
case DisplayMessage.AlertContext.Success:
    <svg .../>
    break;
```

That way you can avoid the double quotation marks and Html.Raw, etc.

**Comment by AnukratiMehta** [comment]
> This is great! Everything is working perfectly and I'm getting the correct icons in all places. There's just one detail that needs to be tidied up now.
> 
> I know that .NET Razor syntax can be odd since it switches between C# and HTML, and sometimes it doesn't work the way you expect. But in the switch statement in "_AlertPartial", you can just output the SVG code directly instead of saving everything to a string first:
> 
> ```
> case DisplayMessage.AlertContext.Success:
>     <svg .../>
>     break;
> ```
> 
> That way you can avoid the double quotation marks and Html.Raw, etc.

Thanks, @dougwaldron. Please check now.

**Review by dougwaldron — APPROVED** [review]
Great work, @AnukratiMehta! Thanks for your contributions, and thanks also for sticking with it through all my requested changes!

**Pull request merged**
